// ADD YOUR OWN KEYS AND RENAME THIS FILE TO keys.js
const TWITTER_TOKENS = {
  TWITTER_CONSUMER_KEY: "PoKc1VEH0e4Uyx9J5QgcN7x05",
  TWITTER_CONSUMER_SECRET: "hwLuxVPcTMkyPbmJgzKXcGzTOUxjgZnHY13WxKPYppxnrCytUK",
  TWITTER_ACCESS_TOKEN: "150253857-LE2RP8gGOU6R1ErBil0zJNEtLWMgPxMJUz1q8X5V",
  TWITTER_TOKEN_SECRET: "acCogIrGPIclqcOtPqPmPQgDE6swJqLqwl7LCQFgqjAOA"
};

const DB_USER = "SOME USER";
const DB_PASSWORD = "SOME PASSWPORD";
const MONGODB = {
  MONGODB_URI: `mongodb://${DB_USER}:${DB_PASSWORD}@ds<SOME_DOMAIN>.mlab.com:<PORT>/<PROJECT_NAME>`
};

const SESSION = {
  COOKIE_KEY: "thisappisawesome"
};

const KEYS = {
  ...TWITTER_TOKENS,
  ...MONGODB,
  ...SESSION
};

module.exports = KEYS;
