const TWITTER_TOKENS = {
  TWITTER_CONSUMER_KEY: "EERtxmc67IodIN35E2R3Msvw8",
  TWITTER_CONSUMER_SECRET: "FuTYamp2ETWXgNpFDyfn6wwFvoE1qrR0am0he4Nfq0gbgUjprK",
  TWITTER_ACCESS_TOKEN: "150253857-apuo7BEvLpDRkXNINcY35ZJp6pNchj0qBB14Pa7p",
  TWITTER_TOKEN_SECRET: "E6R25e9anB1qpWeAI2Kc0y0l7k1GchArcmNIifEsgREn0"
};

const SESSION = {
  COOKIE_KEY: "thisappisawesome"
};

const KEYS = {
  ...TWITTER_TOKENS,
  ...SESSION
};

module.exports = KEYS;
